export const HOME_ROUTE = '/'
export const SECTION_ARTICLES_ROUTE = '/articles/:section'
export const ARTICLE_ROUTE = '/articles/:section/:article'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const PERSONAL_ACCOUNT_ROUTE = '/my/main'
export const LOGIN_REMINDER_ROUTE =  '/login/reminder'
export const LOGIN_RECOVER_ROUTE =  '/login/recover/:link'


export const ADMIN_ROUTE = '/admin'
export const ADMIN_ARTICLE_CREATE_ROUTE = '/admin/article/create'
export const ADMIN_ARTICLE_UPDATE_ROUTE = '/admin/article/update'
export const ADMIN_ARTICLE_LIST_ROUTE = '/admin/article'
export const ADMIN_ARTICLES_UPDATE_ROUTE = '/admin/articles/update'

export const ADMIN_HOME_ARTICLE_CREATE_ROUTE = '/admin/article/home/create'
export const ADMIN_HOME_ARTICLE_UPDATE_ROUTE = '/admin/article/home/update'
export const ADMIN_HOME_ARTICLE_LIST_ROUTE = '/admin/article/home'
export const ADMIN_HOME_ARTICLES_UPDATE_ROUTE = '/admin/articles/home/update'
